---
title: "Comparison of missing data handling methods for variant pathogenicity predictors"
author: 
- name: "Mikko Särkkä"
  affiliation: 
    - 1
    - 2
- name: "Sami Myöhänen"
  affiliation: 
    - 1
- name: "Kaloyan Marinov"
  affiliation: 
    - 1
- name: "Inka Saarinen"
  affiliation: 
    - 1
- name: "Leo Lahti"
  affiliation:
    - 3
- name: "Vittorio Fortino"
  affiliation:
    - 2
- name: "Jussi Paananen"
  affiliation: 
    - 1
    - 2
affiliation:
- name: "Blueprint Genetics Ltd, Helsinki, Finland"
  id: 1
- name: "University of Eastern Finland, Institute of Biomedicine, Kuopio, Finland"
  id: 2
- name: "University of Turku, Department of Future Technologies, Turku, Finland"
  id: 3

bibliography: references.bib
biblatexoptions: "sorting=none"

...


